DMMS-010 user-management rest api
nowicki-maciej/dmms-app pull request #4
Opened 2019-03-21 23:39 UTC by michal-krajewski

2019-03-22 00:01 UTC, nowicki-maciej requested changes

2019-03-22 00:01 UTC, nowicki-maciej commented on user-management/README.md
> +GET `/users/current` - returns full data of logged user
include methods into code section

2019-03-22 00:01 UTC, nowicki-maciej commented on user-management/src/main/java/cf/dmms/app/usermanagement/api/UserController.java
> +    private void verifyPasswords(String password, String repeatedPassword) throws PasswordsMismatchException {
It could be verified by annotation in DTO

2019-03-22 00:01 UTC, nowicki-maciej commented on user-management/src/main/java/cf/dmms/app/usermanagement/api/UserController.java
> +    public ResponseEntity updateUser(@Valid @RequestBody FullUpdateUserDto userDto) throws PasswordsMismatchException{
Body of this method indicates that user can only update himself (currentUser.id == dto.id). Why then is he pre authorized as admin?

2019-03-22 00:01 UTC, nowicki-maciej commented on user-management/src/main/java/cf/dmms/app/usermanagement/api/UserController.java
> +        if(currentUser().getId().equals(userId)) {
If we allow user to only manage himself, request like this should be trated like FORBIDDEN, not BAD_REQUEST, as bad request usually indicates malformed request body

2019-03-22 00:01 UTC, nowicki-maciej commented on user-management/src/main/java/cf/dmms/app/usermanagement/api/UserManagementController.java
> +//    @PostMapping("/manage/{userId}")
Are those method and controller necessary?

2019-03-22 00:01 UTC, nowicki-maciej commented on user-management/src/main/java/cf/dmms/app/usermanagement/user/DefaultUserService.java
> +    public List<BasicUserDto> findAllUsers() {
Read doesn't need to be transactional

2019-03-22 00:01 UTC, nowicki-maciej commented on user-management/src/main/java/cf/dmms/app/usermanagement/user/DefaultUserService.java
> +        userRepository.save(user);
single operation does not need to be transactional

2019-03-22 00:01 UTC, nowicki-maciej commented on user-management/src/main/java/cf/dmms/app/usermanagement/user/DefaultUserService.java
> +        userRepository.save(user);
As above

2019-03-22 00:01 UTC, nowicki-maciej commented on user-management/src/main/java/cf/dmms/app/usermanagement/user/DefaultUserService.java
> +    public void updateUser(FullUpdateUserDto userDto) throws UserNotFoundException {
It should be possible to avoid using 2 different methods for updating current user and user in overall. Both of them are users anyway.

2019-03-22 00:01 UTC, nowicki-maciej commented on user-management/src/main/java/cf/dmms/app/usermanagement/user/UserMapper.java
> +    public static User mapToUser(RegistrationUserDto userDto, PasswordEncoder encoder) {
Consider `toDto` and `toEntity` names

2019-03-22 00:01 UTC, nowicki-maciej commented on user-management/src/main/java/cf/dmms/app/usermanagement/user/dto/RegistrationUserDto.java
> +    @NotNull
`@NotBlank` is better
You could also verify length, especially on login field

2019-03-22 00:06 UTC, michal-krajewski commented on user-management/src/main/java/cf/dmms/app/usermanagement/api/UserController.java
> +        if(currentUser().getId().equals(userId)) {
In my opinion this is bad request, admin can't delete himself.

2019-03-22 00:07 UTC, michal-krajewski commented on user-management/src/main/java/cf/dmms/app/usermanagement/api/UserController.java
> +    public ResponseEntity updateUser(@Valid @RequestBody FullUpdateUserDto userDto) throws PasswordsMismatchException{
There is "BAD_REQUEST" returned if currentUser.id == dto.id.
It's safety feature to ensure that admin won't change his own role to user.

2019-03-22 00:08 UTC, michal-krajewski commented on user-management/src/main/java/cf/dmms/app/usermanagement/api/UserManagementController.java
> +//    @PostMapping("/manage/{userId}")
Nope, forgot to delete.

2019-03-22 00:13 UTC, nowicki-maciej commented on user-management/src/main/java/cf/dmms/app/usermanagement/api/UserController.java
> +    public ResponseEntity updateUser(@Valid @RequestBody FullUpdateUserDto userDto) throws PasswordsMismatchException{
Then change bad request to forbidden

2019-03-22 00:14 UTC, nowicki-maciej commented on user-management/src/main/java/cf/dmms/app/usermanagement/api/UserController.java
> +        if(currentUser().getId().equals(userId)) {
It's a forbidden operation :D

2019-03-23 11:00 UTC, nowicki-maciej requested changes

2019-03-23 11:00 UTC, nowicki-maciej commented on user-management/src/main/java/cf/dmms/app/usermanagement/user/dto/UpdateUserDto.java
> +            @JsonProperty("email") @Email String email) {
Double validation is not necessary. Leave it only on field

2019-03-23 11:00 UTC, nowicki-maciej commented on user-management/src/test/cf/dmms/app/usermanagement/user/dto/DtoValidationTest.java
> +    private List<ConstraintViolation<Object>> validationResults;
Convert it to local variable. It's not necessary for it to be class-scoped variable.

2019-03-23 11:00 UTC, nowicki-maciej commented on user-management/src/test/cf/dmms/app/usermanagement/user/dto/ValidationTestBase.java
> +    static List<String> extractMessages(List<ConstraintViolation<Object>> validationResults) {
`ConstraintViolation<Object>` -> `ConstraintViolation<?>` to increase useability

2019-03-23 11:15 UTC, nowicki-maciej commented on user-management/src/test/cf/dmms/app/usermanagement/user/dto/DtoValidationTest.java
> +    private List<ConstraintViolation<Object>> validationResults;
`validator.validate(...)` return `Set<ConstraintViolation<T>>`, so change it to set, and stop using those `addAll(...)` apache methods please

2019-03-23 11:16 UTC, nowicki-maciej commented on user-management/src/test/cf/dmms/app/usermanagement/user/dto/ValidationTestBase.java
> +    static List<String> extractMessages(List<ConstraintViolation<Object>> validationResults) {
Also remember to change this method to accept `Set` or even better for maximum portability just accept `Collection<ConstraintViolation<?>>`

2019-03-23 11:17 UTC, nowicki-maciej commented on user-management/src/test/cf/dmms/app/usermanagement/user/dto/ValidationTestBase.java
> +    static List<String> extractMessages(List<ConstraintViolation<Object>> validationResults) {
The general rule here is:
* accept least specific interface possible
* return highest specific interface possible

2019-03-23 12:00 UTC, nowicki-maciej approved these changes

2019-03-23 12:01 UTC, merged